---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-kustomized-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./test_kustomized_app/
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-kustomized-app
  validation: client
